# Generated by Django 3.0.7 on 2020-06-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
