# Generated by Django 3.0.7 on 2020-06-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drogas', to='farmacia.Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='droga',
            unique_together={('nombre', 'cantidad', 'empresa')},
        ),
    ]
