# Generated by Django 3.0.7 on 2020-06-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_auto_20200618_2121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='droga',
            unique_together={('nombre', 'cantidad')},
        ),
    ]
