# Generated by Django 3.0.7 on 2020-06-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.IntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='juego.Profesion')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nivel_min', models.IntegerField()),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='juego.Profesion')),
            ],
        ),
    ]
